### ISSUE TITLE
error: package directory 'projects/PointRend/point_rend' does not exist

### ISSUE THREAD

**Issue by omid-reza** [natureyoo/ContinualTTA_ObjectDetection#10]
Hi,

When i want to run `python -m pip install -e <folder_name>`

I get the following error:

error: package directory 'projects/PointRend/point_rend' does not exist

**Comment by San-dow** [comment]
> Hi,
> 
> When i want to run `python -m pip install -e <folder_name>`
> 
> I get the following error:
> 
> error: package directory 'projects/PointRend/point_rend' does not exist

Yes, I've met the question as you too. May I ask if this problem has been solved.

(ctta_od) PS C:\Users\xx\Desktop\Invincible\ContinualTTA_ObjectDetection> pip install -e .
Obtaining file:///C:/Users/xxx/Desktop/Invincible/ContinualTTA_ObjectDetection
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running egg_info
      creating C:\Users\xxx\AppData\Local\Temp\pip-pip-egg-info-q3oh35_u\detectron2.egg-info
      writing C:\Users\xxx\AppData\Local\Temp\pip-pip-egg-info-q3oh35_u\detectron2.egg-info\PKG-INFO
      writing dependency_links to C:\Users\xxx\AppData\Local\Temp\pip-pip-egg-info-q3oh35_u\detectron2.egg-info\dependency_links.txt
      writing requirements to C:\Users\xxx\AppData\Local\Temp\pip-pip-egg-info-q3oh35_u\detectron2.egg-info\requires.txt
      writing top-level names to C:\Users\xxx\AppData\Local\Temp\pip-pip-egg-info-q3oh35_u\detectron2.egg-info\top_level.txt
      writing manifest file 'C:\Users\xxx\AppData\Local\Temp\pip-pip-egg-info-q3oh35_u\detectron2.egg-info\SOURCES.txt'
      error: package directory 'projects\PointRend\point_rend' does not exist
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


# #Yes, I've met the question as you too. May I ask if this problem has been solved.

**Comment by San-dow** [comment]
It is worth noting that the torch1.11.0 provided by the author matches cu118 and cannot be found on the official website.
