### ISSUE TITLE
About training sample access

### ISSUE THREAD

**Issue by sxyxs** [natureyoo/ContinualTTA_ObjectDetection#2]
Hi,

Thank you for the great work and congratulations on your paper being accepted by CVPR 2024. When reading your paper, I noticed that you pre-computed a feature distribution from the training set (source domain data) before starting adaptation. Which means, it is not source free. Am I understand it correctly?

**Comment by natureyoo** [comment]
Yes, obtaining source statistics is easy and requires minimal work during the training phase. Additionally, we only use source feature statistics such as mean and variance to estimate the feature distribution, so the storage required is minimal compared to model checkpoints. Thank you for your interest!

**Comment by sxyxs** [comment]
Thanks for the clarify!
