### ISSUE TITLE
Cannot access Source pre-trained models

### ISSUE THREAD

**Issue by sxyxs** [natureyoo/ContinualTTA_ObjectDetection#3]
Hi,

It seems the model CKP link is not public. Could you please change the permissions? Thank you!

**Comment by Z-Z188** [comment]
May I ask how do you address this problem?

**Comment by sxyxs** [comment]
> May I ask how do you address this problem?

no solution

**Comment by Z-Z188** [comment]
> > May I ask how do you address this problem?
> 
> no solution
Hello, did you get through this code? Can I ask you a few questions? I can give pay.

**Comment by sxyxs** [comment]
Not yet, do you have problems with detectron2 or their implementation?

**Comment by Z-Z188** [comment]
I cannot run the “bash script/coco..”
my QQ is 3426047355. Can you add it.&nbsp; Thanks!!!

---Original---
From: "Xiangyu ***@***.***&gt;
Date: Wed, Jul 10, 2024 18:42 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [natureyoo/ContinualTTA_ObjectDetection] Cannot access Sourcepre-trained models (Issue #3)




 
Not yet, do you have problems with detectron2 or their implementation?

**Comment by natureyoo** [comment]
Sorry for being late. I modify the drive to be accessible via link. It provides COCO-Corrupted dataset, source model checkpoint for COCO, and feature statistics. Please let me know if you have any further issues.

**Comment by Z-Z188** [comment]
> Sorry for being late. I modify the drive to be accessible via link. It provides COCO-Corrupted dataset, source model checkpoint for COCO, and feature statistics. Please let me know if you have any further issues.

Thank you very much！！！
