### ISSUE TITLE
ModuleNotFoundError: No module named 'tutel'

### ISSUE THREAD

**Issue by twangnh** [natureyoo/ContinualTTA_ObjectDetection#7]
could you please specify how do you install tutel, which is used in detectron2 `detectron2/modeling/backbone/swin.py`

**Comment by NgTMDuc** [comment]
Have you solved this problem, can I ask your help?

**Comment by Sapphire-356** [comment]
I successfully installed Tutel using the following command:
```
python3 -m pip install -v -U --no-build-isolation https://github.com/microsoft/tutel/archive/refs/tags/v0.2.0.tar.gz
```
